version: '3.4'

services:
  payments:
    image: ${DOCKER_REGISTRY-}payments
    build:
      context: .
      dockerfile: PAYMENTS/Dockerfile
    ports:
      - "5001:443"
      - "5011:80"
  acme-backend:
    image: ${DOCKER_REGISTRY-}acmebackend
    build:
      context: .
      dockerfile: acme-backend/Dockerfile
    ports:
      - "5000:443"
      - "5013:80"

  shipping:
    image: ${DOCKER_REGISTRY-}shipping
    build:
      context: .
      dockerfile: SHIPPING/Dockerfile
    ports:
      - "5002:443"
      - "5022:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_serveracme
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Abc*123!
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver-data:/var/opt/mssql

  facturacion:
    image: ${DOCKER_REGISTRY-}facturacion
    build:
      context: .
      dockerfile: FACTURACION/Dockerfile
    ports:
        - "5004:443"
        - "5034:80"

volumes:
  sqlserver-data:


